### ISSUE TITLE
Training with expired contact info cannot be edited in the admin  

### ISSUE THREAD

**Issue by ic4f** [usegalaxy-eu/tiaas2#8]
Training with expired contact info (GDPR) cannot be edited in the admin due to the validation of the email field (`<gdpr-redacted>` is not a valid email).

**Comment by hexylena** [comment]
It can, just provide a dummy email there. (But we could make that value a more email-like value.)

**Comment by ic4f** [comment]
> It can, just provide a dummy email there. (But we could make that value a more email-like value so you don't have to update the email every time.)

We may be able to do even better and automate it away. I'll have a PR later today.

**Comment by ic4f** [comment]
Fixed in #14
